### ISSUE TITLE
Passing build args in multi-stage build using a terminal stage dockerfile

### ISSUE THREAD

**Issue by rverma-nikiai** [docker/cli#1009]
This is a feature suggestion, which I believe would be much useful.

Consider scenario as there is a util (e.g brew) which can install multiple packages 
```
FROM alpine:3.7 as build

ONBUILD ARG CLOUD
ONBUILD RUN if [ "${CLOUD}" = "aws" ]; then echo 'installing aws'; fi
ONBUILD RUN if [ "${CLOUD}" = "gce" ]; then echo 'installing gce'; fi
```
As a consumer of this utility, I can install the utilities from the base image, while adding multiple utilities of mine also;
```
FROM my-onbuild
RUN echo 'installing my-super-cool-aws-util'
```
But at final step I would need to build my image as 
`docker build --build-arg CLOUD=aws -t cool .`

It would be nice to have if from final Image (**cool** here)  I define those args within docker file, 
and they are automatically added to build context's args even for builder image
```
FROM my-onbuild
ARG CLOUD=aws
RUN echo 'installing my-super-cool-aws-util'
```
Raising it in cli repo as 1 quick way to handle this is, scan the current docker file add all non-null args as build-args (if not already added).

Thanks

**Comment by thaJeztah** [comment]
Haven't tried (writing from my phone), but have you tried if it works if you define the default on a global level? ie;

```Dockerfile
ARG CLOUD=aws
FROM my-onbuild
RUN echo 'installing my-super-cool-aws-util'

**Comment by rverma-nikiai** [comment]
@thaJeztah It works, thanks a lot.

**Comment by thaJeztah** [comment]
Great!

**Comment by DaWoody** [comment]
Hi @thaJeztah I was hoping you could help me answer a quick question about passing variables between multi-staged builds in a Dockerfile, **without** using global arguments. To make it more clear of why I am asking this.

My use-case (snippet from a fictive Dockerfile) is something like this:

```Dockerfile
FROM alpine AS pre_install
# extract node-version from file here, pseudo-code something like
NODE_VERSION=$(echo $(cat .nvmrc))
# Now I want to build the second build stage where the real stuff happens
FROM node-alpine:${NODE_VERSION} AS build_app
# .. do stuff here..
```

... The problem is ofc how its possible to pass the `NODE_VERSION` variable into the second build-stage, hence I prior to this do not yet have that information. I cannot use a global `ARG NODE_VERSION` before the first `FROM`, here since the information is extracted from the content within the build folder (Where the Dockerfile resides)

Ofc I can do stuff prior to this using *bash/shell* and script stuff... but that is not at all as clean as making it work directly in Docker. It should be possible to make it work **without** resorting to external scripts and then calling `docker build --build-arg=NODE_VERSION -t cool-app-name:1.0.0 .`

Any idea on how can I do this ?

Thanks a lot in advance 🌞!
Cheers!

**Comment by thaJeztah** [comment]
You can't set Dockerfile variables from the result of a shell command (and no, a local `ARG` cannot be used to set a global arg).

**Comment by DaWoody** [comment]
@thaJeztah ok Thanks for the answer! Which is: its not possible from within a Dockerfile to generate a value that will later be used in latter multistage FROM section ( the pattern according to the code snippet provided). I must know outside of the Dockerfile what version I am to use in all or any FROM sections in a single or multistaged build Dockerfile?
