### ISSUE TITLE
SwitchDaemon should take platform as argument

### ISSUE THREAD

**Issue by abergs** [docker/cli#1042]
The docker CLI has a -SwitchDaemon argument that switches between linux and windows containers.
However, it's just a switch and doesn't allow specifying which platform you want to run, which makes it really hard to use in a predictable manner in automation scenarios.

**Comment by ndeloof** [comment]
Hi.

Despite a confusing name, `DockerCli.exe` you're using is Docker for Windows UI command line; can you reopen this in [https://github.com/docker/for-win/issues](https://github.com/docker/for-win/issues) so that it gets the attention from the maintainers?

I'm closing this issue, as docker/cli (the `docker` command line) is not involved here
