### ISSUE TITLE
How docker port forwarding works and differs from socat?

### ISSUE THREAD

**Issue by amir3code** [docker/cli#1193]
Using docker I can run a container:  

    docker run --name bash --privileged -p 443:443 -p 443:443/udp -d bash

It opens the port `443` on the host and redirect both `tcp` and `udp` packets to it.  

But using `socat` I can only use `tcp` or `udp` only one of them in a time:  

    socat tcp-listen:443,fork tcp:172.18.0.3:443
    # OR
    socat udp-listen:443,fork udp:172.18.0.3:443

How docker can handle both at the same time but `socat` can not?  
What utilities does docker uses to achieve this?  
Can `socat` do that with just another command?

**Comment by cpuguy83** [comment]
What error is socat giving?

Docker is doing two things:

1. Sets up port forwards in iptables
2. Starts a userspace proxy to handle local traffic (because hairpinning is not supported without some extra options on dockerd).

The userspace proxy is just doing a standard bind.

**Comment by amir3code** [comment]
`socat` does not give any errors actually it works fine, but it works only in one protocol at a time.  
The reason I posted this issue was to know how docker forwards these ports to each other.  
I use `lxc` and I want to forward ports similar to docker but I didn't find a tool that can handle both tcp and udp **at the same time**  ( please tell me if im wrong, is really docker doing 2 things at the same time or is it just two iptables rules the firewall is checking sequentially? :| )

secondly: If it adds iptables rules what is the need for a proxy? Isn't just using iptables sufficient for port forwarding?

thirdly: What proxy tool does docker use? What do you mean a standard bind? Netcat? do you mean this?

    mkfifo namedpipe;
    nc -l 443 0<namedpipe | nc 172.18.0.3 443 1>namedpipe;

**Comment by cpuguy83** [comment]
> tool that can handle both tcp and udp at the same time

Ah, you mean handling both in a single process?
It's totally possible, but docker actually starts up a helper process for each addr/port/proto as I recall just for simplicity. Nothing really stopping it from doing them all at the same time other than the interface.

>  If it adds iptables rules what is the need for a proxy? Isn't just using iptables sufficient for port forwarding?

Partly for history, partly because of bugs that (at least used to) exist in the kernel... but basically docker sets an iptables rule so that all local traffic gets sent to the userspace proxy as it was not possible to have local traffic (traffic originating from the host back to itself) be NATed.
There is an option to enable this functionality and skip the userspace proxy: `--userland-proxy=false`. This enables the hairpin NAT functionality.

Even with hairpin NAT enabled, Docker will still bind on the specified ports to make sure that:
1. Nothing else is using that port
2. Nothing else tries to use that port later

> What proxy tool does docker use? What do you mean a standard bind? Netcat? do you mean this?

Docker uses it's own proxy, it's in https://github.com/docker/libnetwork

By `bind`, I mean this: http://man7.org/linux/man-pages/man2/bind.2.html
Bind is a system call which assigns the addr/port to a socket.
