### ISSUE TITLE
Unused packages in vendor directory

### ISSUE THREAD

**Issue by aaronlehmann** [docker/cli#120]
The vendor directory has `github.com/docker/docker-credential-helpers/secretservice` and `github.com/docker/docker-credential-helpers/osxkeychain`, but these don't appear to be imported anywhere. We should investigate if this is a bug in `vndr`.

cc @tiborvass

**Comment by dnephin** [comment]
I looked into this when I was creating the vendor for `docker/cli`. `vndr` will preserve directories if they contain `.h` files but no `.py` or `.cc` files (https://github.com/LK4D4/vndr/blob/4a288dfdfc143affcf94002c0f5b241996f03a5e/clean.go#L15-L27).

Both of these directories contain `.h` files, so that's why it's keeping them.
