### ISSUE TITLE
Support relative paths with bind mounts (volumes)

### ISSUE THREAD

**Issue by borekb** [docker/cli#1203]
As previously discussed in https://github.com/moby/moby/issues/4830, it would be useful to be able to bind-mount relative paths like this:

```
docker run --mount type=bind,source=host-dir,target=/app ...
```

> Note: The original issue suggests `docker run -v host-dir:/app ...` which might (probably?) be confused with named volumes so I think it's more likely to expect it from the newer `--mount` option.

The two main motivations for this are:

- Consistency with docker-compose.
- Ability to write cross-platform `docker run` commands, e.g., we have a npm script that currently does something like `"start": "docker run -v $PWD:/app ..."`. It's not easy at all to write a command that would work across Linux, macOS and Windows today.

**Comment by JonasJR** [comment]
This would be verry helpful! Been looking for this but havent found any good solution....

**Comment by prankymat** [comment]
In my opinion, it is explicit and makes sense to resolve the path as relative path instead of absolute if the bind mount path starts with a `./`.

For example:

```sh
docker run -v ./data-dump:/app/dump my-image
```

`./` resolves as relative path in `docker-compose` as well which makes perfect sense and should be supported in docker cli as well imho.

**Comment by FelschR** [comment]
Coming from `docker-compose` that supports relative paths for volumes I would've expected docker itself to support it.

**Comment by Downchuck** [comment]
Seems like this one got dropped on contributor agreement -- otherwise looks like an easy one to get through.

**Comment by prankymat** [comment]
Would highly appreciated if there’s any updates regarding this issue.

**Comment by Downchuck** [comment]
@prankymat looks like it failed the automated tests on a rw label

**Comment by gpapin** [comment]
You can always use replace `.` by `$(pwd)` to achieve the same result in the meantime Like so : `docker run -v $(pwd)/data-dump:/app/dump my-image`

**Comment by borekb** [comment]
@gpapin You can't, your example won't work in some shells on Windows. See the original post where this is mentioned.

**Comment by gpapin** [comment]
You are right @borekb, this is just a workaround for linux like you mentioned in your original post.

**Comment by prankymat** [comment]
Casual ping that I've addressed this in #1273 which just passed all the tests. Would be more than happy if any moderators could help review it! 😄

**Comment by FireEmerald** [comment]
As workaround for `$(pwd)`, try instead ` -v %cd%\on\host:/opt/inside/container` which should work under windows.

**Comment by Lewiscowles1986** [comment]
> Coming from `docker-compose` which supports relative paths for volumes I would've expected docker itself to support it.

docker-compose does not support this on all OS's. Windows for example is a nightmare for relative mounting regardless of ${PWD} and other what I'd term "hacks"

I don't understand why as OSx is also running in a VM, no matter how lightweight, vagrant and all VM technologies support this. It's crazy that since it's valuation, docker hasn't really innovated much at all.

**Comment by thaJeztah** [comment]
From the above, I (personally) think it'd be ok to allow relative paths; with the constraints that relative paths _MUST_ start with a period (`.`) and either followed by a path separator (`/` or `.\\`), or a colon (for the `-v` shorthand syntax); that way, relative paths can be used _both_ for the `--mount` _and_ for the `-v` / `--volume` short-hand syntax (without the ambiguity between `some-dir` being a volume name or a directory named `some-dir`).

I guess _technically_ we _could_ implement some smart logic to handle relative paths without a leading `./` by first checking if `some-dir` exists in the current directory, and if so, expand it to the full path, otherwise treat it as volume-name, but I'm not too keen on that approach; this may lead to unexpected results, similar to [MinGW and MSYS trying to be smart](https://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line) (which caused a lot of grieve).


Let me ping some other people who may have thoughts/opinions on this;  @tianon @cpuguy83 @tonistiigi @AkihiroSuda @silvin-lubecki @justincormack @crazy-max

**Comment by cpuguy83** [comment]
I'm totally fine with it, compose already does this.
Probably will be good to take extra care in the docs to point out that relative such paths need to exist on the host machine but the client will be the one resolving the path.
