### ISSUE TITLE
Network priority not implemented in docker-compose version 3.0

### ISSUE THREAD

**Issue by combin** [docker/cli#1372]
I have docker-compose.yml v3.0 and i have issue from https://github.com/docker/compose/issues/4645. [Acording by documentations](https://docs.docker.com/compose/compose-file/#networks) it is not implemented in 3.0. Is it planned to implement it? Or is there any reason why this feature was removed?

```
# docker-compose --version
docker-compose version 1.22.0, build f46880f
```
```
# docker --version
Docker version 18.06.1-ce, build e68fc7a
```

**Comment by kddubb** [comment]
+1  Interested in a response to this and when this will make it into v3?

**Comment by Daniel-Valentine** [comment]
+1 as well.

**Comment by fago** [comment]
Running into this as well. 
That and having it to automatically add a network alias with the service name is problematic when using traefik. See https://forums.docker.com/t/multiple-networks-in-a-docker-compose-file-precedence/39071

**Comment by unglaublicherdude** [comment]
+1 from me as well. We have a Swarm with thousands of containers running and some networks are basically used in every deployed stack for most services.

We have sometimes the case, that the network where all the traffic is in (because of the problem mentioned here), just doesn't respond anymore when at the same time, the communication via the stacks default networks works just fine. This is a real issue for us. As Workaround we now prefix the default-networks of all stack with aaaa manually now.

**Comment by dpiquet** [comment]
+1 ! This is also an issue for us. Also using traefik.

**Comment by flikkes** [comment]
+1 ! as this is also an issue for us. We'd like to be able to rely on the order the networks IP addresses are added to /etc/hosts so we can use the first address as a default for certain configuration parameters. So being able to rely on the first network in the list being actually treated as the first one would be great!

**Comment by frgomes** [comment]
+1

**Comment by epica-shai** [comment]
+1

**Comment by volking0** [comment]
+1

**Comment by willopez** [comment]
+1

**Comment by thelittlefireman** [comment]
+1

**Comment by fhaferkorn** [comment]
+1

**Comment by jfellus** [comment]
I may be wrong but it seems to me that docker-compose's implementation doesn't make a difference between v2 and v3. Connections are indeed created from an OrderDict sorted by priority, no matter v2 or v3 is used (see https://github.com/docker/compose/blob/master/compose/network.py#L325, and PR https://github.com/docker/compose/pull/5566 clearly show that v3 is ok since at least jan 2018)

Could anyone who know what happens next on the docker side explain why this priority isn't taken into account (BTW v2 and v3 priorities are equally ignored) ? 
A rapid test https://gist.github.com/jfellus/cfee9efc1e8e1baf9d15314f16a46eca shows that network interfaces are allocated following lexical order of network names, despite any priority settings.

1. If I'm wrong, it would be great to make clear in the docs why v3 isn't displaying this cool feature, while v2 docs are still showing it albeit it doesn't really work... https://docs.docker.com/compose/compose-file/compose-file-v2/

2. If I'm right, could someone propose an addition to v3 docs to close misleading issues such as this one ? And eventually explain why it may have worked in the past (is it really the case ?)

thanks !

**Comment by pwatk** [comment]
+1 This is real pain. Please fix this.

**Comment by mendorf-ebf** [comment]
+1, besides respecting the [compose spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md#priority) for docker stack deploy which is still not allowing to mix v2 and v3... :(

**Comment by mmathie** [comment]
+1 Network priority not being available is really annoying. Prefixing network names works for now, but thats not a solution.

**Comment by nospam2000** [comment]
We use a macvlan network as secondary network for non ip based protocols (PROFINET IO or DCP, based directly on layer 2 ethernet). In the container we need to know the network interface name which is bound to the macvlan ("eth1"). When the order of the network interfaces changes two things happen:
 1. the default gateway gets no longer set to the network interface used for normal ip based communication, because only the first interface gets a default gw setting
 2. the network interface names get swapped that means the app will use the wrong network interface for layer 2 based communication over the macvlan interface

Our macvlan network is an external network defined by the company which delivers the OS running on the device.
The additional networks are defined by the developers of the apps which run on that device.
It is really annoying that we have to call the macvlan network "zzz_layer2_net1" to be halfway safe that it always comes last, because we don't know the name of the other networks which is defined by the app developer.

When a user names the directory which contains his docker-compose.yaml "zzzz_1234" we will get a problem, because docker compose uses this as a project name which will be used as the prefix of the default network name.

This is really annoying, please fix it.

**Comment by ndeloof** [comment]
Network priority is included in the Compose Specification (compose-spec.io) and is supported both by docker-compose 1.28+ and new `docker compose` command in the Docker CLI.

**Comment by flikkes** [comment]
> 
> 
> Network priority is included in the Compose Specification (compose-spec.io) and is supported both by docker-compose 1.28+ and new `docker compose` command in the Docker CLI.
> 
> Based on this, IMHO this issue could be closed (cc @thaJeztah)

Well, was it fixed?

**Comment by ndeloof** [comment]
Created https://github.com/docker/compose-cli/issues/1785 as a follow-up issue to investigate correct implementation in Compose v2
