### ISSUE TITLE
docker stack deploy -f reference flag 

### ISSUE THREAD

**Issue by JvnB** [docker/cli#1457]
https://docs.docker.com/engine/reference/commandline/stack_deploy/#compose-file

I still find:

`docker stack deploy --compose-file docker-compose.yml -f docker-compose.prod.yml vossibility`

should be 

`docker stack deploy --compose-file docker-compose.yml --compose-file docker-compose.prod.yml vossibility` ?

_Originally posted by @JvnB in https://github.com/docker/cli/issues/976#issuecomment-430223492_

**Comment by thaJeztah** [comment]
Thanks for reporting!
Looks like the source file is correct, 
https://github.com/docker/cli/blob/master/docs/reference/commandline/stack_deploy.md, but has not yet been deployed on docs.docker.com

that's being tracked through https://github.com/docker/docker.github.io/issues/7358, so let me close the issue here
