### ISSUE TITLE
Plugins can't re-use the same flags as cli global flags

### ISSUE THREAD

**Issue by silvin-lubecki** [docker/cli#1699]
**Description**
A plugin can't use the same name as one of the cli global flags (`debug`, `log-level`, `context`, ...), or worse can't use the same shortcut (ex: `-c`).

If I add a new flag to the `hello-world` plugin like this following:

```go
flags.StringVarP(&compose, "compose", "c", "", "compose file")
```

and try to use it:
```console
$ docker helloworld -c my-compose-file.yml
unable to resolve docker endpoint: context "my-compose-file.yml" does not exist

$ docker --help
...
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker context use")
```

This context flag is a root command flag, not a PersistentFlag and so shouldn't be used by the docker cli and forwarded directly to the plugin.

**Comment by ijc** [comment]
I think (fairly sure) this might relate to 935d47bbe967808f69f5b7c72fc848a08f447c2d (which was basically the same problem but for unknown arguments).

Basically when cobra parses the command line it knows when it hits a new subcommand (since it has a list), but if it hits something (without a `-` or a`--`) which it doesn't know about it accumulates as a argument to the previous command. So e.g.:
```
docker app -c foo.yml
```
It accumulates `app` as an argument to `docker`, not as a new subcommand, and since it is therefore still in the "context" of the `docker` command when it hits the `-c` it treats it as the global, instead of falling through to the "I don't know what `app` is, try a plugin" path.

This is going to be tricky to address I think -- right now, due to how cobra works, I can't think of a way to address this without always adding a stub command for every plugin we find at start of day (implying a scan of the plugins on each invocation). I'll investigate what can be done on the cobra end, up to and perhaps including patching it, before it comes to that though.

**Comment by thaJeztah** [comment]
ah, yes, I ran into this as well 😞
