### ISSUE TITLE
Docker cli plugins called using `--help`, even when its not the plugin's turn

### ISSUE THREAD

**Issue by SvenDowideit** [docker/cli#1812]
I had a quick play with 19.03 beta1 and added `docker-prune`

interestingly, my plugin gets called when running `docker system prune  --help`, `docker system --help prune` , and `docker --help system prune`

but not when calling `docker system prune` or `docker system prune -f`

I presume the problem is that `--help` is implemented in a very special way...

@ijc

**Comment by ijc** [comment]
> my plugin gets called 

I suppose it is the `docker-cli-plugin-metadata` entrypoint which is called, not any sort of `--help` on the plugin?

That's needed because of the way cobra handles help processing, we need to add stub entries for all the plugins so we get the opportunity to call the plugin (if help was run on it) instead of getting `unknown command`. It should only be for help (not regular invocation) and only calling the metadata endpoint so I think that is tolerable. WDYT?

**Comment by ijc** [comment]
Ping @SvenDowideit can you confirm that it is only the `docker-cli-plugin-metadata` endpoint which was unexpectedly called?

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
