### ISSUE TITLE
container_linux.go:247: starting container process caused "exec: \"./script.sh\": stat ./cplace.sh: no such file or directory"

### ISSUE THREAD

**Issue by joaoribmartins** [docker/cli#1873]
I've following Dockerfile:
```
FROM openjdk:8-jdk-alpine

# Install ImageMagick
RUN apk add --no-cache imagemagick
# Run as unprivileged user 'cplace'
RUN adduser -D cplace && chown -hR cplace /home/cplace
USER cplace

WORKDIR /home/cplace

# Copy the current directory contents into the container at /home/cplace
ADD . /home/cplace

# Install cplace
RUN unzip software.zip && \
	rm software.zip

# Make port 8083 available to the world outside this container
EXPOSE 8083

ENTRYPOINT ["./script.sh"]
```
I can create the image and run the container without problems on my local machine.
Once I push it to my openshift environment, docker throws following error:

> container_linux.go:247: starting container process caused "exec: \"./script.sh\": stat ./script.sh: no such file or directory"

Any Idea what can be wrong here?

Thank you in advance
Joao

Output of `docker version on my local machine`:**
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

**Comment by thaJeztah** [comment]
What version of Docker is running in openshift?

**Comment by joaoribmartins** [comment]
> What version of Docker is running in openshift?

docker-1.13.1

**Comment by thaJeztah** [comment]
That's a really old version of Docker; Docker 1.13 reached EOL over two years ago, and hasn't been maintained since; I'd highly recommend running a currently supported version, because older versions have known (unpatched) vulnerabilities, including container escapes (which allow a container's process to break out of the container and potentially obtain root access on the host).

If the `docker-` prefix is part of the actual version that it's showing, you're likely running the Red Hat fork of Docker, which is not maintained here, and which has known to have various issues in the past (there's a _lot_ of custom changes in those versions).

I'll close this issue because this is an issue with a version of Docker that reached EOL, but feel free to continue the conversation
