### ISSUE TITLE
Simple way to make all environment variables of the host accessible from inside Docker

### ISSUE THREAD

**Issue by probonopd** [docker/cli#2210]
Please provide a **simple** way to make all environment variables of the host accessible from inside Docker, thanks.

Use case: I am building on Travis CI inside Docker containers, and need access to all the environment variables outside of the Docker container.

**Comment by thaJeztah** [comment]
This is not something we'd likely implement, because it would take away the separation that containers provide (and having such an option would be risky, as it would give containers access to, e.g., secrets such as AWS tokens without the user explicitly choosing to do so).

If should not be too difficult to achieve this with a bash script though; the following script will fetch all environment variables from the current environment and set a `-e ENV_VAR_NAME` for each of them. Setting `-e ENV_VAR_NAME` (without an `=` or `=some-value`) will set an environment variable (`ENV_VAR_NAME`) for the container, and take the value of `$ENV_VAR_NAME` from the current environment (without explicitly passing the value on the command-line, so slightly reducing the risk of exposing/leaking the env-var value in, e.g. your bash-history or in some log-file.

```bash
#!/bin/bash

IFS=$'\n'
for e in $(env); do
	env_vars="-e ${e%%=*} $env_vars"
done
unset IFS

exec docker run --rm $env_vars busybox env
```

**Comment by probonopd** [comment]
Thanks for the workaround @thaJeztah. Was hoping for a simple command line switch like `--use-host-env` though, but I understand your explanation.

**Comment by thaJeztah** [comment]
Let me close this issue for now, because there's a workaround for this use-case, and I don't think we'd currently want to implement this, but feel free to continue the conversation.
