### ISSUE TITLE
Make the repository, tag and image ID available for docker registries when pushing an image.

### ISSUE THREAD

**Issue by eyalbe4** [docker/cli#2233]
When pushing a docker image to a registry, the following values related to the pushed image are not available for the registry: repository, tag and image ID.
Would it be possible to add these values to the request which pushes the blogs (for example, as headers). so that the registry can access them?

Thanks

**Comment by thaJeztah** [comment]
Can you describe the use-case? I don't think this is part of the distribution specification (https://github.com/opencontainers/distribution-spec); blobs are pushed to the registry, after which the manifest is pushed that correlates the blobs with the manifest ("image")

**Comment by eyalbe4** [comment]
Sure @thaJeztah,

For a registry that applies permissions on what images can be pushed, it allows the registry to verify that blobs can be pushed early on, otherwise the point of permission check has to be deferred to the very end until the manifest is pushed. 

With this change, blobs that are not permitted to be pushed can be rejected immediately if needed by looking at image name:tag information, saving resources and futile work for both the registry and the client.

I would also gladly submit a PR to help promoting this functionality. 
Thanks

**Comment by thaJeztah** [comment]
Such a change would be breaking compatibility with anything currently used; it would mean that any system currently used to push images would no longer be able to (if the registry rejects blobs that do not have this information); the first step for getting this implemented would be to open a proposal for changing the specification.

**Comment by eyalbe4** [comment]
@thaJeztah,
This change can be backward compatible. The suggestion is to add information to the request. If the additional information is there, the registry can chooae to use it.
Please let me know what you think.

**Comment by thaJeztah** [comment]
> This change can be backward compatible. The suggestion is to add information to the request. If the additional information is there, the registry can choose to use it.

The registry changes would not be backward compatible: it would reject blobs that are pushed by any client that doesn't provide this information (many millions of current installs, in addition to other clients, not just "docker"). By enforcing it, such a registry would not be compliant with the distribution specification.

For other registries, the extra information would be just "noise", without any added value.

So, for a change like this, this really should be accepted as part of the distribution spec first, so that the exact behavior and meaning of this information is defined, and to allow other clients and registries to implement it (if needed).


That said; wondering: doesn't the [bearer token](https://docs.docker.com/registry/spec/auth/jwt/) already contain information about the repository that will be pushed to? (so, wouldn't it reject a push to a repository that the user doesn't have access to?)

**Comment by eyalbe4** [comment]
@thaJeztah,
Thanks for your reply and the information provided.
This issue can be closed.
