### ISSUE TITLE
Can't remove images after reinstall docker-ce. Error: No such image: xxx

### ISSUE THREAD

**Issue by CwjXFH** [docker/cli#2349]
Hi,

I  followed [document](https://docs.docker.com/v17.09/engine/installation/linux/docker-ce/centos/) reinstall docker-ce on centos. Before I reinstall, I didn't delete the existing images, when I completed reinstall, I remove the image will get an error: **No such image:xxx**.

I try the command :`  docker system prune`, it doesn't work.

![](https://user-images.githubusercontent.com/11468733/74840440-f4aaf880-5361-11ea-9bf8-8cf1790c7916.PNG)

**Comment by CwjXFH** [comment]
I delete all image files from `/var/lib/docker/image/overlay2/imagedb/content/sha256` and `/var/lib/docker/image/overlay2/imagedb/metadata/sha256`.
Then exec `docker images`, no images info display. But I don't know if it will have a negative impact.

**Comment by thaJeztah** [comment]
What version do you have installed now, and what version were you running before?

If you previously installed the Red Hat fork of Docker, then that may be related; the Red Hat fork of docker contains many modifications to the upstream source, some of which are incompatible, and could cause issues like this

**Comment by CwjXFH** [comment]
I installed docker use `yum install docker` command on centos7, the docker version is 1.13(maybe).

I want to use multi-stage build, so I need to update docker, I reinstall docker followed the docker official document, now my docker version is 19.03.6.

**Comment by thaJeztah** [comment]
The 1.13 version sounds like the Red Hat fork indeed, so that may explain it;

```
Available Packages
docker.x86_64                                                                       2:1.13.1-102.git7f2769b.el7.centos                                                                       extras
docker.x86_64                                                                       2:1.13.1-103.git7f2769b.el7.centos                                                                       extras
docker.x86_64                                                                       2:1.13.1-108.git4ef4b30.el7.centos                                                                       extras
```

The official packages are in the `download.docker.com` apt/yum repository, and packages are named `docker-ce` (for the "engine"),  `docker-ce-cli` (for the cli), and `containerd.io` (containerd runtime).

While the installation instructions describe removing the distro (red hat) packages; https://docs.docker.com/install/linux/docker-ce/centos/#uninstall-old-versions, removing those packages won't remove your existing images/containers, but unfortunately that may cause problems in your case due to the Red Hat packages not being compatible 😞 

If you don't have important information stored in docker (i.e., no "volumes" that still contain important data, and no containers or images that you didn't backup / push to a registry), you could "start from scratch", stop the docker daemon (`sudo systemctl stop docker.service`), and remove the whole `/var/lib/docker` directory. But, as mentioned **this removes all docker data**

**Comment by CwjXFH** [comment]
OK, I see, thanks!
