### ISSUE TITLE
docker service update --stop-grace-period does not take effect until next call

### ISSUE THREAD

**Issue by aeroheart-c6** [docker/cli#2441]
I notice `docker service update --stop-grace-period=<time>` does not behave as expected.

The `--stop-grace-period` does not seem to take effect until the next time this same command has been invoked. First call, the command will behave as if `--stop-grace-period` has not been supplied; then the next call will respect the value from the previous call's `--stop-grace-period`.

I've been testing it with my project that runs on Celery (so SIGTERM will wait for running tasks to finish before exiting). Basically I am working on gracefully shutting down running tasks  when the worker gets a SIGTERM by, instead of waiting, I actively mark the tasks to retry, but the stop-grace-period was preventing my logic to finish even though I have given it ample time.

To simplify, I also wrote a simple Python script that catches a SIGTERM -- and there, I made it sleep for an amount of time to allow me to observe. The command I use is:

`docker service update --force --stop-signal=SIGTERM --stop-grace-period=5m <service>`

Apparently, `docker service scale` is also affected by this which is a good thing, but suffers the same strange behaviour.

**Steps to reproduce the issue:**
1. Run a program that catches the SIGTERM signal as a service
2. Run the `docker service update` command
3. Observe container logs

**Describe the results you received:**
The container will be prematurely killed, disrespecting the value in `--stop-grace-period`

**Describe the results you expected:**
The container will not be permaturely kiled and will wait the specified time at most before being killed.

**Additional information you deem important (e.g. issue happens only occasionally):**
First invocation of the command will prematurely kill container. Succeeding invocations will respect the `--stop-grace-period`

**Output of `docker version`:**

```
Client:
 Version:           19.03.8-ce
 API version:       1.40
 Go version:        go1.14
 Git commit:        afacb8b7f0
 Built:             Mon Mar 16 22:23:09 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14
  Git commit:       afacb8b7f0
  Built:            Mon Mar 16 22:22:53 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.3.m
  GitCommit:        d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 68
 Server Version: 19.03.8-ce
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: jwrzxvetcxj6jg9y61mb8oiwa
  Is Manager: true
  ClusterID: dnp6w7rfjfke9t45f948x2tuv
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.1.153
  Manager Addresses:
   192.168.1.153:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.5.11-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.6GiB
 Name: setsuna
 ID: 76QQ:NLB4:I2D4:Y62E:ZFE7:JIWA:JFXN:NK5K:IYBH:HAQ4:ICAZ:OP3T
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Also happens on a Mac OSX machine.

**Comment by thaJeztah** [comment]
Perhaps I'm misunderstanding your description, but I think that's the expected behavior.

1. create a service (default `--stop-grace-period` is `10s`)
2. run `docker service update --stop-grace-period=5m`
   - at this point the service still has the definition that the `--stop-grace-period` is 10 second. It updates the service definition, which started the reconciliation cycle, terminates the old tasks/containers (which have a 10 second `--stop-grace-period`), and creates new tasks/containers, which have a `5m` `--stop-grace-period`

**Comment by aeroheart-c6** [comment]
Hi @thaJeztah ,

Looks like I misunderstood the behaviour of the command. I had expected that these flags would apply before the container was restarted (maybe the command manual wasn't explicit enough...or maybe because I express-learned Docker).

I actually had the fortune of seeing this happen in `docker service inspect` as well shortly before I saw this response in my mailbox and I realized it with a, "oh damn". Your comment confirms things for me, thanks for that!

**Comment by thaJeztah** [comment]
No worries! Glad it's clear now 😅

**Comment by struanb** [comment]
@thaJeztah What was the thinking behind making `--stop-grace-period`, `--update-delay`, `--update-order`, and `--update-parallelism` apply only to newly launched containers?

I too have been tripped up by this intended behaviour, which I'm not sure I find intuitive or helpful.

It makes sense that updates to the behaviour of containers take effect on newly launched containers, but I'm not sure it makes sense that _updates to the update process itself_ should take effect only after an update cycle.

Why not? Sometimes one wants to roll out updates slower than one had previously defined, for example if the time it takes for a new replica to stabilise is higher than normal due to external factors. It seems there's no way to increase --update-delay without first going through an update cycle first, which could result in downtime.

Similarly, perhaps one has misconfigured one's service with `--update-order=stop-first` or `--update-parallelism=100`, and needs to roll out an update. If load is such that the service can't cope with so many replicas being stopped before new ones are started, and there's no way to change the update order before initiating the update, then downtime would seem a certainty.

For these reasons, I would think it desirable that update options affecting the update process have immediate effect.

**Comment by thaJeztah** [comment]
@struanb it's not specific to these options, it's how swarm services work; containers ("tasks") created by swarm services are considered immutable; changes in the service definition that modify the container definition will create new containers/tasks to replace the old ones.

**Comment by struanb** [comment]
Ok thanks. It sounds like a design decision that the parameters controlling the update process for tasks has been made an immutable part of the container definition.

For the record, this doesn't seem like a great design decision, for the reasons outlined above, in short: the desired update process for a task should be a function of _what you want now_, rather than _what you thought was a good idea in the past_.

If what you want now is your update process to be dictated by how you defined your task, then fine; that sounds like a common requirement.

But in general and in principle, that update process should be capable of being overriden by what the operator wants now.

This is because limitations of existing tasks, or changes in the external environment in which those tasks are running, shouldn't mean downtime is an inevitable consequence of updating those tasks.

**Comment by struanb** [comment]
Hi @thaJeztah I've been considering your answer further. It makes sense in the case of certain of the update parameters, perhaps even `--stop-grace-period`.

But what I'd really like to know is this: why do service update parameters that cannot be considered container properties, like `--update-delay` and definitely `--update-parallelism`, need to modify the container definition in the first place?

If these changes to these parameters of the _service definition_ did not need to modify the _container definition_, then it would be possible to make changes to these parameters without starting a reconciliation cycle, which is what I think we would like to achieve.
