### ISSUE TITLE
Make error message clearer when the running kernel doesn't match the installed one

### ISSUE THREAD

**Issue by mnme** [docker/cli#2528]
Every time after I update my kernel and try to start a conatiner with `docker run` before rebooting, docker can't create the network bridge and errors out with an `operation not supported` message.

```
docker: Error response from daemon: failed to create endpoint affectionate_lichterman on network bridge: failed to add the host (veth7b1d49a) <=> sandbox (veth28533ca) pair interfaces: operation not supported.
```

This is not an issue for me, as I know that I have to reboot my machine to get it working again, but for someone new to docker, this could be confusing. I think docker could greatly improve the user-friendliness by adding either a) a note that you probably have a kernel version mismatch between the running and the installed one or b) an additional check with a clear error message.

I don't know if this happens on all platforms, I am running ArchLinux.

**Comment by thaJeztah** [comment]
Thanks for reporting.

The `operation not supported` sounds like a `ENOTSUP` error trickling up from the runtime (and could have many causes). I'm not sure if this situation warrants doing a check for kernel versions _on every request_ that's made. ArchLinux is known for being a "bleeding edge" distro (which is also why we don't officially support it; upgrades often introduce breakage. I think there's also a `docker` package built by the ArchLinux package maintainers, but it's having similar issues due to upgrading components to non-compatible versions).

While upgrading the kernel may be something that happens frequently on ArchLinux, I think it's less of a day-to-day operation on other distributions, and less likely to hit those users (upgrading kernel without a reboot).

**Comment by mnme** [comment]
I don't think that the situation warrants a version check on every request, but doing it _after_ the `ENOTSUP` error occurred could already help with printing a helpful error message.

Anyway, you're definitely right about kernel updates happening much more frequently on ArchLinux than other distros. Nonetheless, bugfix and security updates will happen on other distros too, so I'm not sure how big or small the impact is.

On another note, the root cause is somewhat a mystery for me, as this happens with _every_ kernel update, no matter how small the version jump was. But as you said ArchLinux is not officially supported, so I'm not expecting any support in this regard.

**Comment by thaJeztah** [comment]
I'm closing this ticket, as I don't see us implementing this because of the reasons mentioned. `ENOTSUP` is too generic of an error, so I think this would add too much complexity for mostly a "corner case" issue.

Feel free to continue the conversation though
