### ISSUE TITLE
what's meaning of Exit code 139?

### ISSUE THREAD

**Issue by GitSoftwareNow** [docker/cli#2545]
could you tell me the reason why does the container exit with code 139? https://github.com/docker/for-linux/issues/1019

**Comment by thaJeztah** [comment]
I see you had a reply in https://github.com/docker/for-linux/issues/1019#issuecomment-633410195

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue here
