### ISSUE TITLE
Docker image command Bug.

### ISSUE THREAD

**Issue by ShivamTripathi21** [docker/cli#2565]
I'm not sure whether it's a bug or not, but when I was going through code I found some command level discrepancy.
usually when we run:-
1. docker images
2. docker image ls 
both return the same result as expected but
3.  docker image images
is also returning the same result. is it expected? because I never heard of it.

and also when you run:- docker image -help
it doesn't show images as a subcommand but images work, so it seems like a valid bug.

**Comment by ShivamTripathi21** [comment]
[Code Link](https://github.com/docker/cli/blob/82de74a5e3a745d29c96227f5c16914736411bda/cli/command/image/list.go#L53)
During calling newListCommand, you are calling NewImagesCommand first and that is why images is also working.

**Comment by thaJeztah** [comment]
Hmm. yes, looks like it's "valid" from a technical perspective, but still interesting / confusing. Perhaps we're able to check if the command is called as `docker image ls` or as `docker images` (top-level), and produce an error 🤔.

Looks like a "corner case", so not top-priority, but would be "nice" to fix (contributions welcome if the fix is not adding too much complexity)
