### ISSUE TITLE
Misleading error when using --volumes-from DOESNOTEXIST, docker complains about the image

### ISSUE THREAD

**Issue by jamshid** [docker/cli#2594]
**Description**

Docker gives a misleading error when using --volumes-from where the container does not exist -- docker claims the image does not exist. 

This looks like the same bug found last year:
https://github.com/docker/distribution/issues/3006
That is probably not a bug for "distribution". I'm not sure this "cli" project is the right place either, it's gotten very confusing trying to determine where to file a "docker" bug!

**Steps to reproduce the issue:**
1. Verify image exists and docker run works:
```
$ docker run -ti --entrypoint=bash fakecsn:8.3.2
[root@e4eb36cc6e27 ]# exit
```
2. Now do the same docker run but with `--volumes-from` referencing an container that does exist. The error is not correct, it complains about the image not existing when the problem is the container in volumes-from does not exist.
```
$ docker run -ti --entrypoint=bash --volumes-from doesnotexist fakecsn:8.3.2
Unable to find image 'fakecsn:8.3.2' locally
docker: Error response from daemon: pull access denied for fakecsn, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

```

**Describe the results you received:**

Misleading error that the image does not exist.

**Describe the results you expected:**

The error should say the container "doesnotexist" does not exist.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:41 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:11:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 42
  Running: 30
  Paused: 0
  Stopped: 12
 Images: 443
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-184-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.66GiB
 Name: docker.tx.caringo.com
 ID: YNPQ:NGJV:B3HW:2W4W:3EDA:I34V:2Q57:SWFR:JRS6:VLBU:HBVY:DULZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=generic
 Experimental: false
 Insecure Registries:
  docker.tx.caringo.com:5100
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
variety of desktop, ubuntu 16 and 18

**Comment by thaJeztah** [comment]
Thanks for reporting; I _think_ I understand what may be happening (actually, there may be an existing issue about this)


`docker run` (under the hood) is a combination of `docker pull` (if image is missing), `docker create`, `docker start`, and `docker attach`.

What happens in this case is that the CLI does a `docker create` (to create the container); if that API call returns a 404 status, it normally means the image that is specified is missing, and a `docker pull` should be done first. _However_ if a linked container is missing, the API also returns a 404, and now the return code is ambiguous; the CLI assumes the 404 is because the image is missing, and thus starts a `docker pull`.


In your case, the `fakecsn:8.3.2` likely is an image that you built locally, but doesn't exist on Docker Hub (so `docker pull fakecsn:8.3.2` fails with the error you mentioned.

If I do the same steps with an image that _does_ exist on Docker Hub, the same problem occurs, but this time the `docker pull` succeeds successfully (even though unneeded, because the image was already there), and the _actual_ error (`No such container: doesnotexist`) is printed;


Make sure the image is already there;

```bash
docker pull busybox
```

Start a container using a non-existing container for `--volumes-from`;

```bash
docker run --rm --volumes-from=doesnotexist busybox
# Unable to find image 'busybox:latest' locally
# latest: Pulling from library/busybox
# Digest: sha256:95cf004f559831017cdf4628aaf1bb30133677be8702a8c5f2994629f637a209
# Status: Image is up to date for busybox:latest
# docker: Error response from daemon: No such container: doesnotexist.
# See 'docker run --help'.
```

I think the solution for this is for the API to return a `400` status (invalid request) instead of a `404`, because even though the linked container is missing, in this case that should be considered an "implementation detail", and considered an invalid request (the user specified an invalid linked container).

**Comment by thaJeztah** [comment]
opened https://github.com/moby/moby/pull/41161 with a fix
