### ISSUE TITLE
No way to pass environment variables with special characters (spaces, etc.)

### ISSUE THREAD

**Issue by mcongy** [docker/cli#2786]
**Description**

After going through the documentation and browsing blog posts, forums, and literally every resource I could find, I didn't manage to find a way to reliably pass environment variables that contain special characters.
The content of my env variables is dynamically generated, and I need to find a reliable way to escape them.

**Steps to reproduce the issue:**
```
docker run --rm -e VAR1= hello <image>
docker run --rm -e "VAR1= hello " <image>
docker run --rm -e 'VAR1= hello ' <image>
docker run --rm -e VAR1=' hello ' <image>
docker run --rm -e VAR1=" hello " <image>
```

So the question is:
What characters need to be escaped?
What is the preferred way to achieve this?

If this is not supported at all, then consider this issue a feature request.

Thank you.

**Comment by cpuguy83** [comment]
I'm not sure I'm following what your issue is.
Quoting around the value is what you need:

```
docker run -it --rm -e FOO="A VALUE" busybox env | grep FOO
FOO=A VALUE
```

If you have something particularly persnickety, you could set the variable in your shell and just pass `-e THE_VAR`, and `docker` will read that from it's env.
I can't think of what might cause such issues, though.

Keep in mind with the CLI you are dealing with the shell more than you are with the docker CLI.

The data itself gets encoded as json and transmitted over HTTP to the docker daemon. So you are limited by whatever json can be encoded as json.

**Comment by mcongy** [comment]
Thanks for answering.

After digging through, I realized the problem is with my terminal, that's strangely parsing command arguments.
After switching to a different terminal, everything works (quoting values is enough).

You can close this issue.
