### ISSUE TITLE
Allow plusses (+) in image names

### ISSUE THREAD

**Issue by mcandre** [docker/cli#2865]
Please++

**Comment by thaJeztah** [comment]
This is not something we can currently do in the CLI (or in the docker daemon), as `+` is not allowed in the distribution spec.

A related discussion can be found in https://github.com/docker/distribution/issues/1201, but now that the specification is part of the OCI, it would have to be accepted by the OCI distribution specs first; https://github.com/opencontainers/distribution-spec

closing this issue because of the above, as this is not something that can be addressed in this repository before the specification allows for this.

**Comment by solarmosaic-kflorence** [comment]
Just FYI looks like there is already a ticket for this in the distribution spec project: https://github.com/opencontainers/distribution-spec/issues/154

**Comment by thaJeztah** [comment]
Ah, thanks for linking; I missed that one 👍
