### ISSUE TITLE
network table in docker-run(1) manpage still broken

### ISSUE THREAD

**Issue by zhsj** [docker/cli#2985]
With docker 20.10.4, the table is still broken. The fix for #2948 is incomplete.

![image](https://user-images.githubusercontent.com/227180/109396384-3191ce00-796c-11eb-807a-30bd4593fd6f.png)

**Comment by thaJeztah** [comment]
Hmmm.. interesting. This feels a bug in `md2man` (or a dependency of it); it seems like it's _first_ wrapping long lines, and _after_ that converts it to a table.

On a wider terminal, I see that the `bridge` column is wrapped at a different word, so that one seems to be wrapped by the shell when rendering (so not during generating the man page - probably because the _source_ is less than a specific width);

<img width="1008" alt="Screenshot 2021-03-09 at 13 28 35" src="https://user-images.githubusercontent.com/1804568/110470690-725fb480-80db-11eb-87f6-2d5ca43cf1b0.png">


However, the `network-name|network-id` line _is_ (and the wrapped part is converted to a new row in the table);

<img width="796" alt="Screenshot 2021-03-09 at 13 19 34" src="https://user-images.githubusercontent.com/1804568/110470851-acc95180-80db-11eb-8b67-fa2d554ade28.png">

**Comment by thaJeztah** [comment]
Perhaps there's a configuration to allow for wider "source" width, or to disable hard-wrapping (more specifically: disable hard-wrapping _tables_) 🤔

**Comment by thaJeztah** [comment]
Narrowed down the issue; it looks like it's wrapping whenever it occurs additional markup within the table cell. In this case `_name_ or _id_` has "name" and "id" _italic_. And `using docker network create command` has back tics around `docker network create`.

**Comment by thaJeztah** [comment]
Opened https://github.com/cpuguy83/go-md2man/pull/69 to fix the bug in gomd2man, and a draft pull request to update go-md2man in this repository to fix it; https://github.com/docker/cli/pull/3005

**Comment by thaJeztah** [comment]
Changes were accepted in go-md2man, and opened a fresh PR to update it https://github.com/docker/cli/pull/3199
