### ISSUE TITLE
Improve UX for images created "40 years ago"

### ISSUE THREAD

**Issue by imjasonh** [docker/cli#2995]
Tools like [`ko`](https://github.com/google/ko), [Bazel's rules_docker](https://github.com/bazelbuild/rules_docker) and [CNCF Buildpacks](https://buildpacks.io) (and many others) build container images reproducibly by default, and as such set the creation date of the image as `1970-01-01T00:00:00Z`, according to advice from https://reproducible-builds.org.

This can lead to confusion among users consuming images built by these tools when they use `docker inspect` (etc) and see that it happily prints that the images were created "`40 years ago`". Each project above has some documentation describing why users shouldn't be worried/confused by this ([example](https://buildpacks.io/docs/reference/reproducibility/), [example](https://github.com/google/ko#why-are-my-images-all-created-in-1970)), but ultimately it's a band-aid.

Since, short of a time machine, it's incredibly unlikely that a container image was _actually_ built in 1970, I think it could make sense for `docker` to interpret `1970-01-01T00:00:00Z` as a special value and print some sentinel string in the output of `docker history` (etc), instead of `40 years ago`. That string could be something like `unset`, `zero`, `omitted`, `reproducible`, or honestly basically anything that when googled led to a page on docker.com describing why that value might be unset. (`-H=false` should still show the full timestamp)

The code change seems relatively simple, here:
https://github.com/docker/cli/blob/70a00157f161b109be77cd4f30ce0662bfe8cc32/cli/command/image/formatter_history.go#L89

Has this been discussed and rejected before? I couldn't find any issues related to this topic.

**Comment by jchester** [comment]
A quick nitpick: buildpacks use 1980 as their source epoch date.

[This is because zipfiles, notably including JARs, have 1st January 1980 as their epoch date](https://github.com/buildpacks/pack/issues/130).

**Comment by ImJasonH** [comment]
> A quick nitpick: buildpacks use 1980 as their source epoch date.

It's true. Buildpacks produces images built "`41 years ago`", while `ko` etc produce images built "`51 years ago`", for roughly the same reasons. Thanks for pointing that out @jchester 

I'd like to treat both of these dates (`1980-01-01T00:00:01Z` and `1970-01-01T00:00:00Z`) as special, and show some other string instead of `XX years ago`.

If an image has a `created` date of any other value, `docker images` should continue to show "`CREATED`: `11 years ago`" or whatever, since that date might have been selected to communicate useful information for some reason. But I think 1980-and-one-second and 1970-and-zero-seconds are special values with special meaning.

**Comment by imjasonh** [comment]
I'd still like to see this happen.

If someone could tell me if a PR to start making this change would he accepted that would be helpful, but I'll probably send a PR anyway if I don't hear anything.

**Comment by vdemeester** [comment]
I think we have to decide what we could write there, but I am +:100: on this 👼🏼
