### ISSUE TITLE
Use more informative pull when use sha256

### ISSUE THREAD

**Issue by sarkiroka** [docker/cli#3021]
**Description**

I can pull or run or anything with an image. But what image? To identify I can use tags or sha256 digest. But when I use tag, it can be change day after day when a new version is available. And when I use digest, I don't know what version is this when read the command.
I think great idea use both of them identifier. for example 
`docker pull nginx:1.19.8@d2925188effb4ddca9f14f162d6fba9b5fab232028aa07ae5c1dab764dca8f9f`

It is more readable and user will sure the image is exactly same on every computer, every time
So, the problem is "what mean this digest?" and "what image under this tag".

**Comment by thaJeztah** [comment]
It's already possible to specify both;

```bash
$ docker pull nginx:1.19-alpine@sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2
docker.io/library/nginx@sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2: Pulling from library/nginx
Digest: sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2
Status: Image is up to date for nginx@sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2
docker.io/library/nginx:1.19-alpine@sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2
```

However, when using the above format, you _are_ pulling by digest; digests always takes precedence, and the tag is ignored, so both of these are equivalent:

```bash
$ docker pull nginxe@sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2
$ docker pull nginx:1.19-alpine@sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2
```

This also means that after pulling an image with `image:tag@digest`, the `tag` won't appear in `docker images` / `docker image ls`. In addition, because the tag is ignored, the `:tag` you specify does not necessarily match the digest you specified (currently, or at any point in time);

So, for example, this also works (because the tag is ignored);

```bash
$ docker pull nginx:you-can-put-any-tag-here@sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2
docker.io/library/nginx@sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2: Pulling from library/nginx
Digest: sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2
Status: Image is up to date for nginx@sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2
docker.io/library/nginx:you-can-put-any-tag-here@sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2
```

This is a limitation of how the distribution spec works (and not easy, or even "impossible" to solve).

**Comment by thaJeztah** [comment]
Based on the above, I don't think there's anything really "actionable" here, so I'll close this ticket, but feel free to continue the conversation.
