### ISSUE TITLE
docker run breaks /dev/console on export

### ISSUE THREAD

**Issue by dkjii-g** [docker/cli#3038]
**Description**

/dev/console is replaced by an empty file on export

**Steps to reproduce the issue:**
1. docker create busybox
2. docker export 7dcad6d6bbce2b8b6796295b4d2cd0b4a2b84eb7c6e0f35c8e91466f7cd1794d -o export.tar

**Describe the results you received:**

tar -xf export.tar && ls -l dev/console

-rwxr-xr-x. 1 root rooti 0 Apr  1 20:16 dev/console

**Describe the results you expected:**

crw-------. 1 root root 5, 1 Apr  1 20:12 /dev/console

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue remains if you:

rm dev/console
mknod dev/console c 5 1
tar -cf ../export.tar .
docker import ../export.tar
docker create <sha>
docker export <sha2> -o export.tar
tar -xf export.tar
ls -l dev/console

**Output of `docker version`:**

```
Client:
 Version:           20.10.0-dev
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        55c4c88966
 Built:             Mon Mar 29 15:01:37 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.2
  Git commit:       363e9a88a1
  Built:            Mon Mar 29 15:03:57 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        fec3683b971d9c3ef73f284f176672c44b448662
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 2
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: tmpfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: de40ad007797e0dcd8b7126f27bb87401d224240)
 Security Options:
  seccomp
   Profile: default
  userns
 Kernel Version: 5.4.97-gentoo
 Operating System: Gentoo/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 11.43GiB
 Name: dev
 ID: RFHR:HTEI:YMR3:2VIS:X7UD:DXMD:DP5U:GFQ2:2XTF:SHYI:WXT4:GUMC
 Docker Root Dir: /var/lib/docker/1000.1000
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Looks similar to your other issue; https://github.com/docker/cli/issues/3037

The reason for this is that `/dev/console` is used as a mountpoint inside the running container;

```bash
docker run --rm -it busybox sh -c 'ls -la /dev/console && mount | grep console'
crw--w----    1 root     tty       136,   0 Jun 16 13:08 /dev/console
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
```

While it would (theoretically) be possible to keep track of all mountpoints that were created, and to remove them / exclude them in the export, this would likely add quite some complexity.

In any case, if this would have to be fixed, this needs to either happen in the engine itself (or perhaps even in containerd or runc). Perhaps you can use tar's `--exclude` option to exclude `/dev`. If you think this is an important issue to fix, I'd recommend opening a ticket in https://github.com/moby/moby instead.

Like your other ticket; if your intent is to export the container's image, then `docker save` / `docker image save` is a better option.

I'm closing this because of the above, but feel free to continue the conversation.
