### ISSUE TITLE
Docker CLI and Docker hub access are still blocked in Sudan

### ISSUE THREAD

**Issue by kabaros** [docker/cli#3084]
**Steps to reproduce the issue:**
1. Go to Sudan
2. Try to pull any docker image

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/1014725/117112009-534e6d80-ad80-11eb-9847-f8c3c561324d.png)

**Describe the results you expected:**

To be able to use Docker normally as Sudan is no longer part of the [US Sanctions List](https://www.reuters.com/article/uk-sudan-usa-sanctions/u-s-lifts-sudan-sanctions-wins-commitment-against-arms-deals-with-north-korea-idUKKBN1CB26E).

**Additional information you deem important (e.g. issue happens only occasionally):**

Sudan is no longer under the US sanctions since November last year. Most US tech companies have updated their services, except a handful including Docker. Here is the amendment to the law (d)(1) (Computer Tier 3 destinations), which will permit the release of technology and source code to Sudanese nationals. https://www.bis.doc.gov/index.php/documents/regulations-docs/federal-register-notices/federal-register-2021/2710-86-fr-4929/file

**Comment by thaJeztah** [comment]
Thanks for reporting; I reached out to our legal team, and they informed me that while some restrictions are lifted, there are still some things to be resolved before Docker Hub is able to remove this block.

This is actively being worked on but (as any legal matter) may take some time.

This repository and issue tracker is for bugs and feature requests for the Docker CLI; for visibility, I'd recommend opening a ticket in Docker's public roadmap instead; https://github.com/docker/roadmap/issues

I'm closing this ticket here because of the above,  but hope my answer helps

**Comment by kabaros** [comment]
@thaJeztah can your legal team be more specific about the issues that need resolving. We've had the same discussion with Algolia, MongoDB and PluralSight, and once we pointed to the [law amendment](https://www.bis.doc.gov/index.php/documents/regulations-docs/federal-register-notices/federal-register-2021/2710-86-fr-4929/file), they opened their services for users in Sudan. I don't know why Docker would be different?

I appreciate this is not a technical issue, but as you might imagine, from the point of view of a developer in Sudan, this is simply discriminatory, so the legal team needs to be a bit more specific about what "things need to be resolved". I'd be happy to contact the legal team directly but there is no way to do so - this is my contact mozafar@nyala.dev.

**Comment by mohammadorbispay** [comment]
Hi is this still blocked for Sudan?
