### ISSUE TITLE
Docker files make a mess of the project directory

### ISSUE THREAD

**Issue by moeiscool** [docker/cli#313]
When i tried to put the docker files into a folder `INSTALL/docker/` in my project directory it said it could not go up in directories or something. Please fix this so docker files do not make a mess of my project's root directory.

I would prefer there are no files specific to docker in the root of my project. Mainly because docker is mostly used as a testing system for my project, not for production use.

Here is my project https://github.com/moeiscool/Shinobi

as you can see the docker files are literally just a mess.

**Comment by cpuguy83** [comment]
The Dockerfile can go anywhere within your project.
`docker build -f path/in/project/Dockerfile .`

**Comment by moeiscool** [comment]
ah i guess my problem is that I was using kitematic when i was trying to do it. When i upload it to docker hub wouldn't it have the same issue when pulling? Is there a way to make docker do this by default through the dockerfile?

**Comment by cpuguy83** [comment]
Once it's on DockerHub, the Dockerfile doesn't do anything at all.

>  Is there a way to make docker do this by default through the dockerfile?

How would this work?

**Comment by moeiscool** [comment]
frankly i have no clue. i tried before and was met with a restriction it seemed. i could try again to show you the error but it may be some time before i get the chance. thanks for your help! i'll see what i can come up with.

**Comment by thaJeztah** [comment]
Closing because the issue looks to be resolved

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

Closing this issue, but feel free to continue the conversation 👍
