### ISSUE TITLE
Detect compose plugin jq/sed pipeline breaks completion script

### ISSUE THREAD

**Issue by mikepqr** [docker/cli#3215]
**Description**

Detect compose plugin jq/sed pipeline introduced in 5a8d7d506cbbe7cd0df3ed3903cb27a90a51e142 fails, breaking completion.

**Steps to reproduce the issue:**
1. Install an old version of docker e.g. 1.13.1-cs9 in my case
2. Install completion `curl -o /etc/bash_completion.d/docker https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker`
3. Launch a new shell, e.g. `exec $SHELL`

**Describe the results you received:**

Error message:

```
template: :1:18: executing "" at <.ClientInfo.Plugins>: can't evaluate field ClientInfo in type types.Info
```

**Describe the results you expected:**

No output and successful docker completion.

**Additional information you deem important (e.g. issue happens only occasionally):**

I am not certain that the problem is caused by my old docker version (rather than a missing plugin), but that seems likely.

Reverting to the completion script before that commit (`curl -o /etc/bash_completion.d/docker https://raw.githubusercontent.com/docker/cli/1148163c3ec90fc78b8f385e065984989b018e8b/contrib/completion/bash/docker`) fixes the problem.

If the goal is to avoid breaking the completion script for very old versions, it seems like guarding the pipeline would be relatively straightforward. cc @ulyssessouza as the author of the commit.

**Output of `docker version`:**

```
template: :1:18: executing "" at <.ClientInfo.Plugins>: can't evaluate field ClientInfo in type types.Info
```

**Output of `docker info`:**

```
Containers: 17
 Running: 17
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 1.13.1-cs9
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 7.527 GB
 Data Space Total: 204 GB
 Data Space Available: 196.5 GB
 Metadata Space Used: 19.73 MB
 Metadata Space Total: 2.143 GB
 Metadata Space Available: 2.124 GB
 Thin Pool Minimum Free Space: 20.4 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.170-RHEL7 (2020-03-24)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6c463891b1ad274d505ae3bb738e530d1df2b3c7
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.27.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26 GiB
Name: mlw0-4.cdsw-int.cloudera.com
ID: V6SW:QMQO:TZTI:BSVS:ALOB:KJXY:KGMA:Z2XR:6SSF:HKO7:JTW6:VDVY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Looks like you're trying to use the completion scripts for the current version of docker on a very old version of Docker that's EOL. You can try downloading the completion-script that matches the version of docker you're running (https://github.com/moby/moby/blob/v1.13.1/contrib/completion/bash/docker), or use the completion script that's included in the Docker package you installed. The package should already install the completion script in `/usr/share/bash-completion/completions/docker`; https://github.com/docker/docker-ce-packaging/blob/5d9ad8ccf9251201a8b436bd09435536e3cfd309/rpm/SPECS/docker-ce-cli.spec#L113-L115

However, I'd highly recommend upgrading to a currently supported version of Docker, as Docker 1.13 reached EOL more than 4 Years ago (the CS version was maintained for some time after that, but also reached EOL), and contains known vulnerabilities

I'm closing this ticket, because this is expected, but feel free to continue the conversation

**Comment by mikepqr** [comment]
I wasn't 100% clear on the "support matrix" for the bash completion script vs prehistoric docker versions, so I guess that answers my question! It's taken this long to break!

I'm totally fine with closing this ticket as expected behavior, but if you'd take a PR to guard the code that doesn't work so it's a no-op rather than a crasher, I'd be happy to take a shot.
