### ISSUE TITLE
Docker connection to containerd not working

### ISSUE THREAD

**Issue by SyngoPredevelopment** [docker/cli#3723]
Hello,

would like to connect the docker cli to containerd containerd runtime in Windows.
The same feature exists in Linux and is achieved by only connecting the dockerd
through --containerd parameter to the running containerd instance.

Under Windows this does not work:
 
Containerd is running as a service on Windows 10, the endpoint:
     "containerdEndpoint": "\\\\.\\pipe\\containerd-containerd"
is the the used (crictl info).

Calling

    dockerd.exe --containerd "\\.\\pipe\\containerd-containerd"

and then doing 

    docker images

does not show the same images as through crictl images.
Also for example 

    --containerd "\\.\\pipe\\containerd-containerd" --containerd-namespace "k8s.io" 

does not help, since the containerd namespace used is "k8s.io".
Tried many other options, no success.

Docker version is 20.10.17 and of containerd 1.6.6.

Attached is also the log of the docker daemon.

Many thanks.
[dockerd.log](https://github.com/docker/cli/files/9219990/dockerd.log)

**Comment by thaJeztah** [comment]
This is currently expected; containerd provides various subsystems, and the Docker Engine currently only uses containerd for the runtime parts, but not yet use the image store and snapshotters. Work is in progress to implement this, and we're planning to have a PoC implementation later this Year (which may not yet be fully complete). 

- see https://github.com/moby/moby/projects/13
- https://github.com/moby/moby/issues?q=is%3Aissue+is%3Aopen+label%3Acontainerd-integration


I'm closing this ticket because of the above, but feel free to continue the conversation

**Comment by SyngoPredevelopment** [comment]
OK, many thanks
