### ISSUE TITLE
security vulnerabilities (HIGH) from golang

### ISSUE THREAD

**Issue by kim-codefresh** [docker/cli#4224]
### Description

on golang.org/x/net/http2/hpack and golang.org/x/net/http2 there are HIGH vulnerabilities

CVE
https://www.cve.org/CVERecord?id=CVE-2022-41723
https://www.cve.org/CVERecord?id=CVE-2022-27664

SNYK
https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2-3028257
https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2HPACK-3358253
https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2-3323837

### Reproduce

CVE
https://www.cve.org/CVERecord?id=CVE-2022-41723
https://www.cve.org/CVERecord?id=CVE-2022-27664

SNYK
https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2-3028257
https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2HPACK-3358253
https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2-3323837

### Expected behavior

scan on the cli image should be clean of HIGH/CRITICAL vulnerabilities

### docker version

```bash
docker cli installation with image 
`https://debian.pkgs.org/11/docker-ce-arm64/docker-ce_20.10.22~3-0~debian-bullseye_arm64.deb.html`

but issue reproduced also on the latest bullseye cli image

https://debian.pkgs.org/11/docker-ce-amd64/docker-ce_23.0.4-1~debian.11~bullseye_amd64.deb.html
```

### docker info

```bash
docker cli installation with image 
`https://debian.pkgs.org/11/docker-ce-arm64/docker-ce_20.10.22~3-0~debian-bullseye_arm64.deb.html`

but issue reproduced also on the latest bullseye cli image

https://debian.pkgs.org/11/docker-ce-amd64/docker-ce_23.0.4-1~debian.11~bullseye_amd64.deb.html
```

**Comment by thaJeztah** [comment]
It looks like this your scan result are for Debian's distro packages, which are not built by us (so not sure what versions of dependencies are used for build those).


Looking at the currently maintained (v23.0.4) release, I see we're already using go1.19.8, and golang.org/x/sys v0.7.0, so either this is a false positive in the scanner, or the Debian packagers use different versions of build-time dependencies;

https://github.com/moby/moby/blob/v23.0.4/vendor.mod#L85
https://github.com/docker/cli/blob/v23.0.4/vendor.mod#L74

Besides that, this vulnerability would at most (but may not even be used) affect connections to the API, which is considered a privileged interface (any user that has access to the API already has the equivalent to `root` access, which means an attacker that can access the API would already have full control.

I'll close this ticket because of the above, but in future, please don't report (potential) security issues through the public issue tracker; https://github.com/docker/cli/blob/master/CONTRIBUTING.md#reporting-security-issues
