### ISSUE TITLE
docker update doesn't work on Windows

### ISSUE THREAD

**Issue by ManoMarks** [docker/cli#453]
we should document that

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by adeniyistephen** [comment]
@ManoMarks @thaJeztah Hello, please is this issue still open? I would love to work on this, Please provide pointers and input on how to work on it. Thanks

**Comment by thaJeztah** [comment]
Looks like this was fixed by https://github.com/docker/cli/pull/454

I'm not a Windows user myself, and the ticket is a bit sparse on details. It would be good if someone could also test what currently happens if you try to run `docker update` / `docker container update` on a Windows container (does it produce a useful error message, or just some obscure error?).

It it does not return a useful error, we should fix that on the daemon side

Let me close this ticket, as the documentation side is fixed, but feel free to continue the conversation 👍

**Comment by adeniyistephen** [comment]
Oh, that’s great. I’m running on an Ubuntu system, I would check on a window system to check for the error. 
👍
