### ISSUE TITLE
Allow to specify only one port in `docker run -p` command if both ports are equals

### ISSUE THREAD

**Issue by scraly** [docker/cli#4585]
### Description

In the `kubectl port-forward` command, a command that allows to connect to a single pod/service in a Kubernetes cluster, the user needs to specify two ports: 

```sh
$ kubectl port-forward <pod-name> <local-port>:<remote_port>
```

But if local port and remote port are the same, "8080" for example, the user need to specify only one port:

```sh
$ kubectl port-forward <pod-name> 8080
```

So I think it can be useful to allow the same things for `docker run -p <local-port>:<container-port> <image-name>:<image-tag>` command, if both ports are equals, why not allowing the user to specify only one port? :-)

**Comment by thaJeztah** [comment]
Unfortunately, we can't implement this, because the `-p` option already allows for a single port to be specified, but with a different meaning; when only specifying a port (but no port to "map" to), docker uses a random port from the ephemeral port range.

For example, in the example below, I start an nginx container, and specify its port `80` to be published, but I don't specify the port to map to it;

```bash
docker run -d -p 80 --name mycontainer nginx:alpine
```

In that case, docker picks a random port, and maps that. In this case, it pisked port `54951`;


```bash
docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED              STATUS              PORTS                   NAMES
e69a71c8877a   nginx:alpine   "/docker-entrypoint.…"   About a minute ago   Up About a minute   0.0.0.0:54951->80/tcp   mycontainer

curl -s 'http://localhost:54951' | grep Welcome
<title>Welcome to nginx!</title>
<h1>Welcome to nginx!</h1>
```

While we _could_ add additional flags to the command (e.g. `--port-forward 80`), typing that would, well, be more than typing `-p 80:80`, so likely would not bring much benefit (beyond discoverability; people already are familiar with the current options).

For that reason, I will close this ticket for now, but the saying "No is temporary, Yes is forever." applies; it's still possible that we'll see reasons to implement this (or a similar option) in future.
