### ISSUE TITLE
What is the container status of 'Dead'?

### ISSUE THREAD

**Issue by johndmulhausen** [docker/cli#502]
@twang2218 commented on [Tue Aug 15 2017](https://github.com/docker/docker.github.io/issues/4211)

File: [edge/engine/reference/commandline/ps.md](https://docs.docker.com/edge/engine/reference/commandline/ps/), CC @johndmulhausen

In the document, it listed a set of possible status, `created|restarting|running|removing|paused|exited|dead`, however, there is no explanation of each status.

I found an article explained some of the status: http://docker-saigon.github.io/post/Docker-Internals/ , but not all of them, especially the `dead` status. What is the difference between `dead` and `exited`?

I think we need some docs explain the lifecycle of a docker container and link the reference here.

**Comment by thaJeztah** [comment]
@johndmulhausen 

"dead" is used for a "defunct" container; for example, a container that you wanted to remove but was only partially removed because resources were kept busy by an external process. Dead containers cannot be (re)started, only removed. You can manually attempt to remove a dead container (if the problem causing  it to not be removed in the first attempt failed), and the daemon will automatically attempt to remove dead containers when it's restarted.

**Comment by sam-thibault** [comment]
Just a note that because our docs are published from the release branch, the new status descriptions won’t be published until it’s in a release branch
