### ISSUE TITLE
rpms for 26.1.4 missing in centos8 repositories

### ISSUE THREAD

**Issue by cesan3** [docker/cli#5364]
### Description

We neet to patch these CVEs on our Rocky8/Centos8 systems

[CVE-2024-24789](https://github.com/golang/go/issues/66869)
[CVE-2024-24790](https://github.com/golang/go/issues/67680)

However, the rpm  `docker-ce-26.1.4-1.el8.x86_64.rpm` and dependencies are not present in https://download.docker.com/linux/centos/8/x86_64/stable/Packages/

### Reproduce

Follow docker installation guide and try to install latest docker community release

### Expected behavior

RPMs are available in the repository

### docker version

```bash
26.1.4
```

### docker info

```bash
NA
```

### Additional Info

I didn't see a better place to report the packaging issue.

**Comment by thaJeztah** [comment]
Thanks for reporting; this is expected, as CentOS 8 reached EOL; https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

Docker also no longer build packages from the v26.x release, only the current (v27.x) releases; see [BRANCHES-AND-TAGS.md](https://github.com/moby/moby/blob/7e864f163c395b902418ff6231179a908079600a/project/BRANCHES-AND-TAGS.md) in the moby repository.

Docker does not currently package for RockyLinux, but you may be able to use the packages for RHEL 8 and RHEL 9; https://docs.docker.com/engine/install/rhel/


I'll close this ticket because of the above, but feel free to continue the conversation.
