### ISSUE TITLE
Feature request - incorporate launch script into image

### ISSUE THREAD

**Issue by wdixon** [docker/cli#548]
Currently there are a significant number of command line options required to start a container (environment vars, volumes, devices, network, etc..), which is often done inside a shell script or a compose file; however, these scripts exist outside of the container, leading to copy/paste of scripts from examples found in the corresponding git repositories and documentation.

What if the image could include default scripts used to launch docker....  

Perhaps the script could be placed inside the container along with a special label to indicate the existence of this script:

LABEL org.docker.launch.scriptA=/app/bin/runA.sh \
           org.docker.launch.scriptB=/app/bin/runB.sh

Then from the cli:

prompt> docker launch scriptA

The launch command could copy the script out of the image onto the host and execute the script, which would ultimately invoke the docker run command. Any error in the script would abort the launch.

**Comment by dnephin** [comment]
This is easy to do without any change to the cli. You can run a script stored as a string in a label:
```
$(docker inspect -f '{{ index .Config.Labels "foo.example" }}' )
```

This is unlikely to be supported by the cli because bash scripts are not portable, so it wont work for most people. The docker run flags aren't stored in the image config for that very reason, they are not portable. Storing them in some other format doesn't make them any more portable.

**Comment by thaJeztah** [comment]
I also think docker-compose files are basically created for this (although not part of the image of course).

I'm closing this for now, because I don't think this will be implemented, but thanks for suggesting, and feel free to continue the conversation
