### ISSUE TITLE
Docker Stats API, how exactly is handled rx,tx with multiple interfaces returned?

### ISSUE THREAD

**Issue by muhahacz** [docker/cli#647]
Hello,
Iam calling API endpoint GET /containers/(id or name)/stats

Response for example:
https://pastebin.com/hhiP5Ve1

How exactly i have to handle with multiple network interfaces (eth0,eth1,eth2) returned by API 
?
Does Docker CLI sums values for all interfaces?

Thanks

**Comment by thaJeztah** [comment]
Yes, you can find the calculations used in the CLI here: https://github.com/docker/cli/blob/dbd96badb6959c2b7070664aecbcf0f7c299c538/cli/command/container/stats_helpers.go#L216-L224

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

If you are developing things using the code in the moby repository, also feel free to ask in the #moby-project channel on the community slack.

I'm closing this issue because of the above, but feel free to continue the conversation 👍
