### ISSUE TITLE
Add JSON output option for docker trust view

### ISSUE THREAD

**Issue by rn** [docker/cli#659]
`docker trust view` is great for humans, but for scripting it would be nice to have an option to also generate the information in JSON or some other format, maybe something like `docker trust view --json <image>`.

**Comment by thaJeztah** [comment]
For that, I'd prefer to have `docker trust inspect`, which historically prints JSON by default

/cc @riyazdf

**Comment by thaJeztah** [comment]
Related; proposal/discussion on https://github.com/docker/cli/issues/522

**Comment by riyazdf** [comment]
@rn: What would you like to script here?  If we translated the exact `docker trust view` info into JSON, is that sufficient or are there certain parameters you would expect?  

We could potentially expose even more information here that we decided to omit from `docker trust view` cc @endophage

**Comment by rn** [comment]
@riyazdf My specific use case is that I want to write a script to check LinuxKit packages to make sure that the manifest lists and the constituent parts are all signed properly. I can obviously just grep for some string in the output but thought it might be nicer to have this a bit more structured.

@thaJeztah Yeah, I was a bit surprised to not see `inspect` and see `view` which I hadn't seen before. Looking at #522 I think having `inspect` for low level stuff and `view` for humans would make sense

**Comment by riyazdf** [comment]
@rn: got it, yes I agree that `docker trust inspect` would be perfect for this

**Comment by thaJeztah** [comment]
> Yeah, I was a bit surprised to not see `inspect` and see `view` which I hadn't seen before. 

You can find the reason in my comment here;  https://github.com/docker/cli/pull/472#pullrequestreview-63738876

Basically, the `inspect` output defaulted to "pretty print". Instead of requiring users to type `docker trust inspect --pretty-print` to read the output, I suggested using `view` instead (with the option to later add an `inspect` function). We made the commands _experimental_ so that we can still change/discuss 👍
